version: '3.1'

services:

  dbdisrup:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      MYSQL_DATABASE: disrup
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - c:\disrup\admin\db:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - disrup
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data

networks:
  disrup:
    driver: bridge